### ISSUE TITLE
Case Sensitive Search

### ISSUE THREAD

**Issue by eng1amer** [figma/plugin-samples#1]
Great work creating the text-search sample code for Figma, but I noticed that it's case sensitive, in other words if I search for "Walk" and there is a text with "walk" in it, it wouldn't find it.

So, I updated the code as I know how [I am no expert], so here's the changes if you want to update your code and make it a public plugin

In the ui.html file

<img width="744" alt="Screen Shot 2019-08-02 at 05 35 32" src="https://user-images.githubusercontent.com/44936822/62340869-b1825880-b4e9-11e9-8850-eb6067edf077.png">

And, in the code.ts

<img width="687" alt="Screen Shot 2019-08-02 at 05 36 20" src="https://user-images.githubusercontent.com/44936822/62340894-d080ea80-b4e9-11e9-94c6-3f08e73e7cac.png">

Thanks

**Comment by jyc** [comment]
Wow, thanks so much for trying out plugins and for fixing our sample :D If you want to file a [pull request](https://help.github.com/en/articles/creating-a-pull-request), I'd be happy to merge it! We could even add case-insensitivity behind a checkbox.

By submitting a pull request, you will even get credit in the Git history for your fix!

If you'd prefer not to, that's fine too, and when I incorporate your fix I'll be sure to credit you. Thanks!

**Comment by jyc** [comment]
I've merged your changes. Thank you @eng1amer! :)
