### ISSUE TITLE
Unable to run plugin code by process

### ISSUE THREAD

**Issue by ZetaoXiao** [figma/plugin-samples#129]
After downloading according to the process and running tsc, the error reported in figma is: Invalid manifest field 'networkAccess', and the URLs in the configuration items are all 404. what should i do next?

**Comment by sharan3102** [comment]
Hey there,
- Check your plugin manifest, Open your manifest.json file and verify the networkAccess field. It should be set to one of the valid values: "NONE", "LOAD_PLUGIN", or "ANY_ORIGIN". Make sure it is correctly formatted and spelled.

- To ensure that your manifest.json file is properly formatted and valid, you can use the Figma Plugin Manifest Validator (https://www.figma.com/plugin-docs/manifest/) or other JSON validation tools. This can help identify any syntax errors or inconsistencies in your manifest file.

**Comment by akbarbmirza** [comment]
The code samples should be updated now and be able to be compiled.
