### ISSUE TITLE
Capital plugin doesn't run

### ISSUE THREAD

**Issue by shantsis** [figma/plugin-samples#130]
Downloading and attempting to run the plugin locally doesn't seem to work, I get an error.

![Screenshot of plugin attempting to run](https://github.com/figma/plugin-samples/assets/22671477/22208b9f-ac01-4083-a653-ca381af1a9c9)
![Screenshot of UI error](https://github.com/figma/plugin-samples/assets/22671477/8f36a84d-d163-4b9f-b6b4-e40bcede8cb8)
![Screenshot of console with errors](https://github.com/figma/plugin-samples/assets/22671477/8a7e7112-919b-4c9f-a146-c4c00c0b7496)

**Comment by 99letters** [comment]
This may no longer be maintained, but it will be in a similar state. Also, don't you need code.js? It also looks like code.js is not uploaded in .gitignore.

**Comment by akbarbmirza** [comment]
Hey all - I updated the code samples a couple months ago to handle some breaking changes in our API. The code should work now. As for needing `code.js` - that's correct. You need to compile the `code.ts` using `tsc` - see the instructions in [Getting Started](https://github.com/figma/plugin-samples?tab=readme-ov-file#getting-started)
