### ISSUE TITLE
Error when launching the plugin styles to variables

### ISSUE THREAD

**Issue by legt** [figma/plugin-samples#135]
I get a error message "peError: Cannot read properties of undefined (reading 'r')"

When i try to run the plugin

<img width="1728" alt="image" src="https://github.com/figma/plugin-samples/assets/10217869/0534b34d-ce73-47a9-b1b6-2fdddb723a31">

**Comment by dinozavrix** [comment]
Hi. There are fixes:
1. line 66, add check that color is solid to ignore gradients
```
 if (paints.length === 1 && paints[0].type=="SOLID") {
```
2. line 44, `VARIABLE_ID` chang to `VARIABLE_ALIAS`

tested via Scripter plugin

**Comment by jshmllr** [comment]
@dinozavrix confirmed that this works in my instance too. Now to just be able to import more than colors.

**Comment by jake-figma** [comment]
this should be resolved now with https://github.com/figma/plugin-samples/commit/61945349684f0fd20848e3f33d1a489427d462e1 from earlier this morning, and https://github.com/figma/plugin-samples/commit/202724a33b5e984d7255ad49de0af2303204fdc8
