### ISSUE TITLE
Transparency blocks variable imports | Variables Import Export plugin

### ISSUE THREAD

**Issue by vandesign** [figma/plugin-samples#138]
I do export of variables and there and then I try import. On the first variable with transparency I get an error

**Comment by jake-figma** [comment]
can you give me an example of the kind of json you are trying to import?

**Comment by jake-figma** [comment]
i take it back. i fixed this color function in my [more sophisticated version of the sample](https://github.com/jake-figma/variables-import-export), but not this one! fix here: https://github.com/figma/plugin-samples/commit/c91a1e2e02d6c6f100d7651d055ef84725adbb5d
