### ISSUE TITLE
Variable export plugin does not export Strings

### ISSUE THREAD

**Issue by seppviljar** [figma/plugin-samples#144]
Using the plugin sample on the official Figma's "Variable playground" results in :

```

/* [ Text ] - Example.English.tokens.json */
{}

/* [ Text ] - Example.German.tokens.json */
{}

/* [ Text ] - Example.Japanese.tokens.json */
{}
```

Any ideas?

**Comment by akbarbmirza** [comment]
Hi @seppviljar - this is a known limitation of our code sample. I've updated the [README](https://github.com/figma/plugin-samples/blob/master/variables-import-export/README.md) to reflect that.

This code sample deliberately only supports types that are currently in the W3C Design Token spec. Strings aren't currently supported in that spec.

You can add that support for yourself, by updating the `traverseToken` function with an `else if` statement for string

```js
else if (type === "string") {
  tokens[key] = createToken(
    collection,
    modeId,
    "STRING",
    key,
    object.$value
  );
}
```

and modifying the `processCollection` function at line 144

```js
if (
  value !== undefined &&
  ["COLOR", "FLOAT", "STRING"].includes(resolvedType)
) {
```

and line 150 

```js
obj.$type =
  resolvedType === "FLOAT" ? "number" : resolvedType.toLowerCase();
```

to account for the string type. You can follow a similar approach for any other types that you might want to add.
