### ISSUE TITLE
Facing issue for Connector options in FigJam Files.

### ISSUE THREAD

**Issue by shyamzzp** [figma/plugin-samples#146]
- Using in Windows10
- Created some small Rectangular Box.
- When zoom >= 35% able to see connectors otherwise not.

Below image is for zoom level 35. 
![image](https://github.com/figma/plugin-samples/assets/8598690/6cd0eb09-8948-4684-80a2-ad186b8f5e62)

Below image is for zoom level less than 35, showing no connectors.
![image](https://github.com/figma/plugin-samples/assets/8598690/aceb8b9f-c9b2-44d1-8414-2030e28c0537)

**Comment by akbarbmirza** [comment]
This does not appear to be an issue related to the plugin samples. Please post about this in the FigJam Bugs forum: https://forum.figma.com/c/figjam/figjam-bugs/
