### ISSUE TITLE
Codegen sample plugin stuck loading

### ISSUE THREAD

**Issue by bburbach** [figma/plugin-samples#165]
When I run the [Codegen sample plugin](https://github.com/figma/plugin-samples/tree/master/codegen) it just gets stuck in a loading loop and doesn't produce any results or errors. @jake-figma @akbarbmirza 

![image](https://github.com/figma/plugin-samples/assets/5395163/b456be26-c5e7-4748-a342-31930cdd8fd8)
![image](https://github.com/figma/plugin-samples/assets/5395163/e19bd5e0-b532-4e2b-b2ef-db33632410a4)

**Comment by akbarbmirza** [comment]
Have you tried reloading the Figma window and running the plugin again?

Can you provide more details, I'm unable to replicate.

**Comment by bburbach** [comment]
Beginner mistake. I had to run `npm run build` first to get it to work.
