### ISSUE TITLE
Could you provide an API to create guide lines?

### ISSUE THREAD

**Issue by haozi** [figma/plugin-samples#173]
![image](https://github.com/user-attachments/assets/d69aa4bc-0adf-4fc6-8db3-1c7e05d82c0d)

Like this, I want to automatically create some guide lines with a script

**Comment by akbarbmirza** [comment]
Hey @haozi - this functionality exists. You can find information about this here: https://www.figma.com/plugin-docs/api/properties/PageNode-guides/

**Comment by haozi** [comment]
thank you, I get it
