### ISSUE TITLE
The getCSSAsync method problem

### ISSUE THREAD

**Issue by justquanyin** [figma/plugin-samples#176]
HI，The return result of the getCSSAsync function has changed in new version .
Now Example:
<img width="761" alt="image" src="https://github.com/user-attachments/assets/152b2b19-7058-4e2e-83d3-7202f9888b9e">

How can I get the data from the previous version? 
Example:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/160ae1c5-5a63-423c-bf3d-e5c0010df310">

**Comment by akbarbmirza** [comment]
Hi @justquanyin - this was caused by an issue on our backend. It should be resolved now - let me know if you're still running into issues.
