### ISSUE TITLE
Variables Import / Export

### ISSUE THREAD

**Issue by phuongddx** [figma/plugin-samples#178]
Hi, 
I'm working on a design system and have created a system color with 4 modes. However, I've encountered an issue where the color code shown when hovering is different from the result after detaching the alias. Have you faced this issue before and can provide some insights? Thank you!

https://github.com/user-attachments/assets/d7417341-af9a-4440-99f9-3803700d51dd

**Comment by akbarbmirza** [comment]
That seems like it might be a bug. Could you please reach out to product support via this form: https://help.figma.com/hc/en-us/requests/new?ticket_form_id=360001731233

That way the team can track and ask you for follow up details as needed
