### ISSUE TITLE
How are people download images from remote URLs before createImage?

### ISSUE THREAD

**Issue by jfrux** [figma/plugin-samples#2]
I'm not seeing a good solid way to download a remote image and inject it.
Obviously it's being done in Unsplash and Google Sheet Sync...

It's looking as if they're being remotely processed via an undocumented API but I cannot find out how to do it?

The images are being ran through this... somehow?
https://www.figma.com/api/upnode/image?purpose=canvas&sha1=32ef6ede498d9bcc86f628f80a609137ef8bb68c&fileKey=34jAAw6DZI3xEM0K75ZnFm

Any tips?

**Comment by jyc** [comment]
Good question! Thanks for checking out plugins in Figma :) We'd prefer you ask questions like this in the Figma Plugins Slack group. That group is pretty active and everyone is very helpful! Also, by doing so others will be able to learn at the same time.

Here is the [invitation link](https://join.slack.com/t/figmaplugins/shared_invite/enQtNjg5NzQ4NTQ4OTAyLWJjOWQyZGRjNmYyZTRmYjk3ZTgzNjJhZTYzZmU5NmJkYzA4MzdjMDFlNzVlM2QwZjhlMGMwMTA5ZWI0N2UxZTA) for that Slack group.

Thanks!
