### ISSUE TITLE
Feature request: replace figma.d.ts from samples/react with @figma/plugin-typings

### ISSUE THREAD

**Issue by Robbie-Cook** [figma/plugin-samples#22]
Hey!

At the moment, figma typings are hard-coded to `figma.d.ts` in the React sample

Similar to #3 , I was wondering if instead of using a `figma.d.ts` file in the React sample, we could add `@figma/plugin-typings` to the dev dependencies, so that users are able to update their figma typings if they change *after* they pull the sample.

Thanks!

**Comment by adispezio** [comment]
Good call out! The typings are now a dev dependency in the root and updated all tsconfigs in the samples to point there. The webpack + react example still pulls its own copy for completeness.
