### ISSUE TITLE
Publish @types/figma to NPM and open a repo for plugin API

### ISSUE THREAD

**Issue by octref** [figma/plugin-samples#3]
I didn't find any other channel where I can post feature requests, thus posting here.

Benefits include:

- Semantically versioned API (plugin authors can easily find breaking changes)
- Easy to download any version of the API

Precedents include [@types/chrome](https://www.npmjs.com/package/@types/chrome) and [@types/vscode](https://www.npmjs.com/package/@types/vscode) (I set it up).

Also I would encourage setting up a GitHub repo for the API. This way people can report bugs or ask API questions in the open.

**Comment by rudi-c** [comment]
Definitely, we'll make sure to do that!

**Comment by rudi-c** [comment]
For general questions/bug reports, we hope to build a developer community where plugin developers can help each other and share resources: https://join.slack.com/t/figmaplugins/shared_invite/enQtNjg5NzQ4NTQ4OTAyLWJjOWQyZGRjNmYyZTRmYjk3ZTgzNjJhZTYzZmU5NmJkYzA4MzdjMDFlNzVlM2QwZjhlMGMwMTA5ZWI0N2UxZTA

**Comment by obenjiro** [comment]
@rudi-c @jyc Hi, can someone please look at this PR? https://github.com/figma/figma-api-demo/pull/16

**Comment by rudi-c** [comment]
@types/figma is now available on NPM

Note that we'll have to monitor how this goes and decide if we necessary want to keep @types/figma available. It's a bit troublesome to have to go through DefinitelyTyped when making API updates as they have their own standards, and now there's confusion regarding what the source of truth is for the typings. But let's wait and see.
