### ISSUE TITLE
html-webpack-inline-source-plugin is no longer maintained

### ISSUE THREAD

**Issue by deanblacc** [figma/plugin-samples#34]
`html-webpack-inline-source-plugin` is no longer maintained and doesn't work with `html-webpack-plugin@^4.0`.
More detailed information can be [found here](https://spectrum.chat/figma/extensions-and-api/cannot-read-property-tapasync-of-undefined-bundling-with-webpack-tutorial-out-of-date~3782c72d-6113-4919-85c8-c91def445579)

**Comment by deanblacc** [comment]
@andrejbroncek hey ! sorry I haven't run into that myself. The only other thing I recall amending was injecting the roll up into the body (was head originally, which was breaking bits) like so:
```
new HtmlWebpackPlugin({
    template: './src/ui.html',
    filename: 'ui.html',
    chunks: ['ui'],
    inject: 'body'
}),
```
Im not sure if that will solve your issue though

**Comment by andrejbroncek** [comment]
> @andrejbroncek hey ! sorry I haven't run into that myself. The only other thing I recall amending was injecting the roll up into the body (was head originally, which was breaking bits) like so:
> 
> ```
> new HtmlWebpackPlugin({
>     template: './src/ui.html',
>     filename: 'ui.html',
>     chunks: ['ui'],
>     inject: 'body'
> }),
> ```
> 
> Im not sure if that will solve your issue though

It did! You are amazing, thanks! Everything works great now :) Hopefully, Figma updates this repo + their documentation.

**Comment by shuta13** [comment]
@deanblacc @andrejbroncek 
Hi, I tried https://github.com/figma/plugin-samples/issues/34#issuecomment-811021237, but it did not work well...

I think it's better to replace it with  [react-dev-utils/InlineChunkHtmlPlugin](https://github.com/facebook/create-react-app/tree/edc671eeea6b7d26ac3f1eb2050e50f75cf9ad5d/packages/react-dev-utils#new-inlinechunkhtmlpluginhtmlwebpackplugin-htmlwebpackplugin-tests-regex) recommended by the author of `html-webpack-inline-source-plugin`

https://github.com/DustinJackson/html-webpack-inline-source-plugin#readme
> This plugin is no longer maintained. Facebook provides a similar plugin:
> https://github.com/facebook/create-react-app/blob/edc671eeea6b7d26ac3f1eb2050e50f75cf9ad5d/packages/react-dev-utils/InlineChunkHtmlPlugin.js#L10

I wrote the following and it worked fine. ( `html-webpack-plugin` v4.x is required)
Please check it !

```javascript
// ---
const InlineChunkHtmlPlugin = require("react-dev-utils/InlineChunkHtmlPlugin");

module.exports = (env, argv) => ({
  // ---
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/ui.html",
      filename: "ui.html",
      chunks: ["ui"],
    }),
    new InlineChunkHtmlPlugin(HtmlWebpackPlugin, [/ui/]),
  ],
});
```
I will create a PR for the updates if needed :)

**Comment by adispezio** [comment]
Just pushed an update moving to webpack 5 which fixes this. I added the version of `InlineChunkHtmlPlugin` from `react-dev-utils` as well. There were lighter-weight versions but FB's is the best maintained.
