### ISSUE TITLE
Being maintained?

### ISSUE THREAD

**Issue by shuta13** [figma/plugin-samples#51]
I think this is a great and useful project for people who make figma plugins!

However, it appears that PRs and issues are no longer being addressed since October 2020. Is it possible that this project is over? Are there any plans to choose a different maintainer or another third party to manage this?

**Comment by adispezio** [comment]
Hey there! Happy to report that we'll be doing a fair amount of cleanup to bring this repo up-to-date in the coming weeks. Stay tuned!

**Comment by shuta13** [comment]
@adispezio 

That's great!! 

I found a few things that need to be fixed, and I'm planning to create a PR soon. I hope this helps!

**Comment by adispezio** [comment]
Yes! I think we're actually tackling some of the same work simultaneously. Just pushed a big update to some of the structure so apologies if anything gets invalidated! I migrated webpack up to 5 and caught quite a few things in the process.

**Comment by adispezio** [comment]
I'm going to close this for now as this is more of a question/umbrella issue and we've made some big updates 😄 Please feel free to open new issues for any smaller, specific things!
