### ISSUE TITLE
Would you mind adding a LICENSE file to the repository?

### ISSUE THREAD

**Issue by KyleWpppd** [figma/plugin-samples#9]
I'd like to use the figma.d.ts types file and some of the example code, but there is no license included.

It looks like the [React example](1) uses the [ISC license](2).

Would it be possible to add the license file to the repo?

Thank you!

[1]: https://github.com/figma/plugin-samples/blob/922e74cf2f1f27b927fb2d5ccea25ac8434ffea2/react/package.json#L10

[2]: https://opensource.org/licenses/ISC

**Comment by adispezio** [comment]
Yes! We've got some big updates coming and will be sure to include a license. In the meantime you can grab the latest copy of our Typings file from npm: https://www.npmjs.com/package/@types/figma.

**Comment by adispezio** [comment]
Fixed in #59 👍
