### ISSUE TITLE
The webpack example does not build.

### ISSUE THREAD

**Issue by ProfessorOakie** [figma/plugin-samples#90]
Just letting you know about this. Also the website link here: https://www.figma.com/plugin-docs/bundling-webpack/ needs to be updated to the new name of the folder. If you're not able to repro the issue then let me know and I can try to help from my side.

**Comment by BranonConor** [comment]
I'm also experiencing this sample project not building - throwing errors about globally declaring console, etc. 

See this issue: https://github.com/figma/plugin-samples/issues/89

**Comment by figmajake** [comment]
sorry for being so late to this. can you try again and see if your issues were resolved by https://github.com/figma/plugin-samples/pull/86

**Comment by John-Oula** [comment]
> sorry for being so late to this. can you try again and see if your issues were resolved by #86

It still does not build

**Comment by jake-figma** [comment]
@John-Oula can you provide the error you are getting and your version of node? on fresh install i am getting the following successful build:

<img width="951" alt="image" src="https://user-images.githubusercontent.com/97200987/204638294-9f59b47e-9f93-401d-9c4c-d14db1e5f109.png">

**Comment by aaronmw** [comment]
Any chance of getting this example revamped using a modern version of Webpack? Or Vite? Even if I get this working, it'll be two years behind 😑
