### ISSUE TITLE
Error: Unable to load code: Error for Trivia and Capital plugins

### ISSUE THREAD

**Issue by pawelkontek** [figma/plugin-samples#91]
![image](https://user-images.githubusercontent.com/7879784/150208939-59d011d5-e1b0-403f-8e33-0f4ab7fb4691.png)
When trying to run plugin (after importing manifest file) the plugin shows error.

**Comment by barnett617** [comment]
> ![image](https://user-images.githubusercontent.com/7879784/150208939-59d011d5-e1b0-403f-8e33-0f4ab7fb4691.png) When trying to run plugin (after importing manifest file) the plugin shows error.

https://forum.figma.com/t/unable-to-load-code-error-at-object-t-getlocalplugincode/7375
